{"uuid": "f8d845cd-5dd4-4bae-a8e9-7565cc8e9539", "children": ["2a147355-65cc-4b14-8dc6-6953afacf1d9"], "befores": [{"name": "create_ui_user", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/m.pecherskiy/Diplom_3/conftest.py\", line 58, in create_ui_user\n    \"accessToken\": data[\"accessToken\"],\n                   ~~~~^^^^^^^^^^^^^^^\n"}, "start": 1724085645260, "stop": 1724085645516}], "start": 1724085645260, "stop": 1724085645523}