{"name": "Просмотр деталей заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@class, 'OrderHistory_dataBox')]\"}\n  (Session info: chrome=127.0.6533.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104ca1024 cxxbridge1$str$ptr + 1887276\n1   chromedriver                        0x0000000104c99700 cxxbridge1$str$ptr + 1856264\n2   chromedriver                        0x00000001048a882c cxxbridge1$string$len + 88524\n3   chromedriver                        0x00000001048ec834 cxxbridge1$string$len + 367060\n4   chromedriver                        0x000000010492448c cxxbridge1$string$len + 595500\n5   chromedriver                        0x00000001048e1474 cxxbridge1$string$len + 321044\n6   chromedriver                        0x00000001048e20e4 cxxbridge1$string$len + 324228\n7   chromedriver                        0x0000000104c68a08 cxxbridge1$str$ptr + 1656336\n8   chromedriver                        0x0000000104c6d464 cxxbridge1$str$ptr + 1675372\n9   chromedriver                        0x0000000104c4e8ec cxxbridge1$str$ptr + 1549556\n10  chromedriver                        0x0000000104c6dc14 cxxbridge1$str$ptr + 1677340\n11  chromedriver                        0x0000000104c405fc cxxbridge1$str$ptr + 1491460\n12  chromedriver                        0x0000000104c8aa5c cxxbridge1$str$ptr + 1795684\n13  chromedriver                        0x0000000104c8abd8 cxxbridge1$str$ptr + 1796064\n14  chromedriver                        0x0000000104c99334 cxxbridge1$str$ptr + 1855292\n15  libsystem_pthread.dylib             0x00000001832d9034 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001832d3e3c thread_start + 8", "trace": "self = <tests.test_orders.TestOrder object at 0x10343cf90>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8fb25023625a2f601faa4cb452ff1200\")>\n\n    @allure.title('Просмотр деталей заказа')\n    @allure.description('Открываем ленту заказов, выбираем первый заказ и проверяем отображение его деталей.')\n    def test_order_info(self, driver):\n        order_feed = OrderPage(driver)\n>       order_details = order_feed.view_order_details()\n\ntests/test_orders.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/page_order.py:19: in view_order_details\n    self.click_on_element(Order.FIRST_ORDER_ITEM)\npages/page.py:19: in click_on_element\n    self.driver.find_element(*locator).click()\n/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10367da50>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...0001832d9034 _pthread_start + 136\\\\n16  libsystem_pthread.dylib             0x00000001832d3e3c thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@class, 'OrderHistory_dataBox')]\"}\nE         (Session info: chrome=127.0.6533.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x0000000104ca1024 cxxbridge1$str$ptr + 1887276\nE       1   chromedriver                        0x0000000104c99700 cxxbridge1$str$ptr + 1856264\nE       2   chromedriver                        0x00000001048a882c cxxbridge1$string$len + 88524\nE       3   chromedriver                        0x00000001048ec834 cxxbridge1$string$len + 367060\nE       4   chromedriver                        0x000000010492448c cxxbridge1$string$len + 595500\nE       5   chromedriver                        0x00000001048e1474 cxxbridge1$string$len + 321044\nE       6   chromedriver                        0x00000001048e20e4 cxxbridge1$string$len + 324228\nE       7   chromedriver                        0x0000000104c68a08 cxxbridge1$str$ptr + 1656336\nE       8   chromedriver                        0x0000000104c6d464 cxxbridge1$str$ptr + 1675372\nE       9   chromedriver                        0x0000000104c4e8ec cxxbridge1$str$ptr + 1549556\nE       10  chromedriver                        0x0000000104c6dc14 cxxbridge1$str$ptr + 1677340\nE       11  chromedriver                        0x0000000104c405fc cxxbridge1$str$ptr + 1491460\nE       12  chromedriver                        0x0000000104c8aa5c cxxbridge1$str$ptr + 1795684\nE       13  chromedriver                        0x0000000104c8abd8 cxxbridge1$str$ptr + 1796064\nE       14  chromedriver                        0x0000000104c99334 cxxbridge1$str$ptr + 1855292\nE       15  libsystem_pthread.dylib             0x00000001832d9034 _pthread_start + 136\nE       16  libsystem_pthread.dylib             0x00000001832d3e3c thread_start + 8\n\n/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException"}, "description": "Открываем ленту заказов, выбираем первый заказ и проверяем отображение его деталей.", "steps": [{"name": "просмотр деталей заказа из ленты заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@class, 'OrderHistory_dataBox')]\"}\n  (Session info: chrome=127.0.6533.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104ca1024 cxxbridge1$str$ptr + 1887276\n1   chromedriver                        0x0000000104c99700 cxxbridge1$str$ptr + 1856264\n2   chromedriver                        0x00000001048a882c cxxbridge1$string$len + 88524\n3   chromedriver                        0x00000001048ec834 cxxbridge1$string$len + 367060\n4   chromedriver                        0x000000010492448c cxxbridge1$string$len + 595500\n5   chromedriver                        0x00000001048e1474 cxxbridge1$string$len + 321044\n6   chromedriver                        0x00000001048e20e4 cxxbridge1$string$len + 324228\n7   chromedriver                        0x0000000104c68a08 cxxbridge1$str$ptr + 1656336\n8   chromedriver                        0x0000000104c6d464 cxxbridge1$str$ptr + 1675372\n9   chromedriver                        0x0000000104c4e8ec cxxbridge1$str$ptr + 1549556\n10  chromedriver                        0x0000000104c6dc14 cxxbridge1$str$ptr + 1677340\n11  chromedriver                        0x0000000104c405fc cxxbridge1$str$ptr + 1491460\n12  chromedriver                        0x0000000104c8aa5c cxxbridge1$str$ptr + 1795684\n13  chromedriver                        0x0000000104c8abd8 cxxbridge1$str$ptr + 1796064\n14  chromedriver                        0x0000000104c99334 cxxbridge1$str$ptr + 1855292\n15  libsystem_pthread.dylib             0x00000001832d9034 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001832d3e3c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/m.pecherskiy/Diplom_3/pages/page_order.py\", line 19, in view_order_details\n    self.click_on_element(Order.FIRST_ORDER_ITEM)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/m.pecherskiy/Diplom_3/pages/page.py\", line 19, in click_on_element\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "клик по нужному элементу", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//a[@href='/feed']\")"}, {"name": "wait", "value": "None"}], "start": 1724085554991, "stop": 1724085555029}, {"name": "клик по нужному элементу", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@class, 'OrderHistory_dataBox')]\"}\n  (Session info: chrome=127.0.6533.120); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104ca1024 cxxbridge1$str$ptr + 1887276\n1   chromedriver                        0x0000000104c99700 cxxbridge1$str$ptr + 1856264\n2   chromedriver                        0x00000001048a882c cxxbridge1$string$len + 88524\n3   chromedriver                        0x00000001048ec834 cxxbridge1$string$len + 367060\n4   chromedriver                        0x000000010492448c cxxbridge1$string$len + 595500\n5   chromedriver                        0x00000001048e1474 cxxbridge1$string$len + 321044\n6   chromedriver                        0x00000001048e20e4 cxxbridge1$string$len + 324228\n7   chromedriver                        0x0000000104c68a08 cxxbridge1$str$ptr + 1656336\n8   chromedriver                        0x0000000104c6d464 cxxbridge1$str$ptr + 1675372\n9   chromedriver                        0x0000000104c4e8ec cxxbridge1$str$ptr + 1549556\n10  chromedriver                        0x0000000104c6dc14 cxxbridge1$str$ptr + 1677340\n11  chromedriver                        0x0000000104c405fc cxxbridge1$str$ptr + 1491460\n12  chromedriver                        0x0000000104c8aa5c cxxbridge1$str$ptr + 1795684\n13  chromedriver                        0x0000000104c8abd8 cxxbridge1$str$ptr + 1796064\n14  chromedriver                        0x0000000104c99334 cxxbridge1$str$ptr + 1855292\n15  libsystem_pthread.dylib             0x00000001832d9034 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001832d3e3c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/m.pecherskiy/Diplom_3/pages/page.py\", line 19, in click_on_element\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \"//div[contains(@class, 'OrderHistory_dataBox')]\")"}, {"name": "wait", "value": "None"}], "start": 1724085555029, "stop": 1724085555037}], "start": 1724085554990, "stop": 1724085555037}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1724085554990, "stop": 1724085555038, "uuid": "cc9dbbea-be52-465e-a5d5-6e01866137f2", "historyId": "6a34d4c75b0ec5d3c1ef22ded8d9308b", "testCaseId": "5410470c83d006d011a7e461d43b4df9", "fullName": "tests.test_orders.TestOrder#test_order_info", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "MacBook-Pro-w-adm-8.local"}, {"name": "thread", "value": "82102-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders"}]}